<#
.SYNOPSIS
    Makes Mailpit start automatically with Windows, with a persistent inbox.

.DESCRIPTION
    SheZen Harmony sends OTP emails over SMTP to 127.0.0.1:1025, which is
    Mailpit. If Mailpit is not running, registration and login fail with a
    connection error, so it needs to be up whenever you work on the app.

    This script writes a small launcher that starts Mailpit hidden (no console
    window) and adds a shortcut to it in your Startup folder. It also points
    Mailpit at a persistent database, so captured mail survives a reboot
    instead of living in a temp file.

    Run it once per machine. No administrator rights required.

.EXAMPLE
    powershell -ExecutionPolicy Bypass -File backend\scripts\mailpit-autostart.ps1

.NOTES
    To undo: delete the "Mailpit" shortcut from shell:startup.
    Inbox:   http://127.0.0.1:8025
#>

[CmdletBinding()]
param(
    # Skip starting Mailpit now; only set up the autostart entry.
    [switch]$NoStart
)

$ErrorActionPreference = 'Stop'

$mailpitDir = Join-Path $env:LOCALAPPDATA 'Mailpit'
$launcher   = Join-Path $mailpitDir 'start-mailpit.vbs'
$database   = Join-Path $mailpitDir 'mailpit.db'
$logFile    = Join-Path $mailpitDir 'mailpit.log'

if (-not (Test-Path $mailpitDir)) {
    New-Item -ItemType Directory -Path $mailpitDir | Out-Null
}

$exe = (Get-Command mailpit -ErrorAction SilentlyContinue).Source
if (-not $exe) {
    $exe = Join-Path $env:LOCALAPPDATA 'Microsoft\WinGet\Links\mailpit.exe'
}
if (-not (Test-Path $exe)) {
    throw "Mailpit is not installed. Run: winget install axllent.mailpit"
}

# VBScript is used purely so the process starts with no console window.
$vbs = @"
' Starts Mailpit in the background at Windows login, with no console window.
' Generated by backend\scripts\mailpit-autostart.ps1 - re-run that to refresh.
' Inbox: http://127.0.0.1:8025
Option Explicit

Dim shell, fso, dbDir, exePath, command
Set shell = CreateObject("WScript.Shell")
Set fso = CreateObject("Scripting.FileSystemObject")

dbDir = shell.ExpandEnvironmentStrings("%LOCALAPPDATA%\Mailpit")
If Not fso.FolderExists(dbDir) Then fso.CreateFolder dbDir

exePath = "$exe"
If Not fso.FileExists(exePath) Then exePath = "mailpit.exe"

command = """" & exePath & """" & _
          " --database """ & dbDir & "\mailpit.db""" & _
          " --max-age 30d" & _
          " --log-file """ & dbDir & "\mailpit.log""" & _
          " --quiet"

' 0 = hidden window, False = do not wait for it to exit.
shell.Run command, 0, False
"@

Set-Content -Path $launcher -Value $vbs -Encoding utf8
Write-Host "Launcher written: $launcher"

$startup  = [Environment]::GetFolderPath('Startup')
$shortcut = Join-Path $startup 'Mailpit.lnk'

$wshell = New-Object -ComObject WScript.Shell
$link = $wshell.CreateShortcut($shortcut)
$link.TargetPath       = Join-Path $env:SystemRoot 'System32\wscript.exe'
$link.Arguments        = "`"$launcher`""
$link.WorkingDirectory = $mailpitDir
$link.Description      = 'Start Mailpit (local SMTP inbox for SheZen Harmony OTP email)'
$link.IconLocation     = "$exe,0"
$link.WindowStyle      = 7
$link.Save()
Write-Host "Startup shortcut written: $shortcut"

if (-not $NoStart) {
    $running = Get-Process mailpit -ErrorAction SilentlyContinue
    if ($running) {
        Write-Host "Mailpit is already running (PID $($running.Id))."
    }
    else {
        & (Join-Path $env:SystemRoot 'System32\wscript.exe') $launcher
        Start-Sleep -Seconds 2
        Write-Host "Mailpit started."
    }
}

Write-Host ""
Write-Host "Inbox:    http://127.0.0.1:8025"
Write-Host "SMTP:     127.0.0.1:1025  (matches MAIL_HOST / MAIL_PORT in backend\.env)"
Write-Host "Database: $database"
Write-Host "Log:      $logFile"
Write-Host ""
Write-Host "To undo, delete: $shortcut"
