@extends('layouts.admin')
@section('title', $questionnaire->exists ? 'Edit questionnaire' : 'New questionnaire')
@section('body')
<main class="content"><a href="{{ route('admin.questionnaires.index') }}">Questionnaires</a><h1>{{ $questionnaire->exists ? 'Edit questionnaire' : 'New questionnaire' }}</h1>
@if($errors->any())<ul class="errors">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul>@endif
<form method="POST" action="{{ $questionnaire->exists ? route('admin.questionnaires.update', $questionnaire) : route('admin.questionnaires.store') }}">@csrf @if($questionnaire->exists)@method('PUT')@endif
<label>Title</label><input name="title" value="{{ old('title', $questionnaire->title) }}" required><label>Description</label><textarea name="description">{{ old('description', $questionnaire->description) }}</textarea>
<div class="field-row"><div><label>Type</label><select name="type"><option value="stress">Stress</option></select></div><div><label>Version</label><input name="version" type="number" min="1" value="{{ old('version', $questionnaire->version ?? 1) }}" required></div><div><label>Status</label><select name="status">@foreach(['draft','published','archived'] as $status)<option value="{{ $status }}" @selected(old('status', $questionnaire->status ?? 'draft') === $status)>{{ ucfirst($status) }}</option>@endforeach</select></div></div>
<label class="remember"><input name="is_active" type="checkbox" value="1" @checked(old('is_active', $questionnaire->is_active))> Active for students</label><label>Published at</label><input name="published_at" type="text" value="{{ old('published_at', optional($questionnaire->published_at)->format('Y-m-d H:i:s')) }}" placeholder="YYYY-MM-DD HH:MM:SS">
<h2>Questions</h2><p class="muted">Select reusable questions and configure their questionnaire order.</p>
@php($selected = old('questions', $questionnaire->exists ? $questionnaire->questions->map(fn($q) => ['id'=>$q->id,'position'=>$q->pivot->position,'is_required'=>$q->pivot->is_required])->all() : []))
@foreach($availableQuestions as $question) @php($configured = collect($selected)->firstWhere('id', $question->id))<div class="field-row"><label class="remember"><input name="questions[{{ $question->id }}][id]" type="checkbox" value="{{ $question->id }}" @checked($configured) onchange="this.closest('.field-row').querySelectorAll('input[data-membership]').forEach(input => input.disabled = !this.checked)"> {{ $question->question_text }}</label><div><label>Position</label><input data-membership name="questions[{{ $question->id }}][position]" type="number" min="0" value="{{ $configured['position'] ?? $question->position }}" @disabled(!$configured)></div><label class="remember"><input data-membership name="questions[{{ $question->id }}][is_required]" type="checkbox" value="1" @checked($configured['is_required'] ?? true) @disabled(!$configured)> Required</label></div>@endforeach
<h2>Score bands</h2><p class="muted">Configure non-overlapping active ranges. Existing unused rows are deactivated when omitted.</p>
@php($bands = old('bands', $questionnaire->exists ? $questionnaire->scoreBands->map(fn($b) => $b->only(['id','code','label','min_score','max_score','position','is_active']))->all() : [['code'=>'low','label'=>'Low','min_score'=>0,'max_score'=>10,'position'=>1,'is_active'=>true]]))
@foreach($bands as $index => $band)<div class="field-row">@if(isset($band['id']))<input type="hidden" name="bands[{{ $index }}][id]" value="{{ $band['id'] }}">@endif<div><label>Code</label><input name="bands[{{ $index }}][code]" value="{{ $band['code'] }}" required></div><div><label>Label</label><input name="bands[{{ $index }}][label]" value="{{ $band['label'] }}" required></div><div><label>Min</label><input type="number" name="bands[{{ $index }}][min_score]" value="{{ $band['min_score'] }}" required></div><div><label>Max</label><input type="number" name="bands[{{ $index }}][max_score]" value="{{ $band['max_score'] }}" required></div><div><label>Position</label><input type="number" min="0" name="bands[{{ $index }}][position]" value="{{ $band['position'] }}" required></div><label class="remember"><input type="checkbox" name="bands[{{ $index }}][is_active]" value="1" @checked($band['is_active'] ?? false)> Active</label></div>@endforeach
<div class="actions"><button class="button">Save questionnaire</button><a class="button button-secondary" href="{{ route('admin.questionnaires.index') }}">Cancel</a></div></form></main>
@endsection
